// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-vreffect.d.ts
declare namespace THREE {
    export class VREffect {
        constructor(renderer: Renderer, callback?: (params: string)=>void);
        render(scene: Scene, camera: Camera): void;
        setSize(width: number, height: number): void;
        setFullScreen(flag: boolean): void;
        startFullscreen(): void;
        FovToNDCScaleOffset(fov: VRFov): VREffectOffset;
        FovPortToProjection(fov: VRFov, rightHanded: boolean, zNear: number, zFar: number): Matrix4;
        FovToProjection(fov: VRFov, rightHanded: boolean, zNear: number, zFar: number): Matrix4;
    }

    export interface VRFov{
        leftTan: number;
        rightTan: number;
        upTan: number;
        downTan: number;
    }

    export interface VREffectOffset{
        scale: number;
        offset: number;
    }
}
